---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: events-data
  labels:
    app: events-data
spec:
  replicas: 2
  selector:
    matchLabels:
      app: events-data
  template:
    metadata:
      labels:
        app: events-data
    spec:
      containers:
      - name: mysql-hibernate
        image: mysql:5.6
        env:
            -name: MYSQL_ROOT_PASSWORD
             value: password
            -name: MYSQL_DATABASE
             value: test
            -name: MYSQL_USER
             value: sa
            -name: MYSQL_PASSWORD
             value: password
      - name: spring-boot-mysql-hibernate
        image: gcr.io/myproject-278611/spring-boot-mysql-hibernate:V_16
        ports:
        - containerPort: 8082
          name: "events-port"
        livenessProbe:
          httpGet:
            path: /
            port: 8082
          initialDelaySeconds: 60
          periodSeconds: 60

---
apiVersion: v1
kind: Service
metadata: 
  name: events-data-service
spec: 
  ports: 
     -  port: 8082
        protocol: TCP
        targetPort: 8082
  selector: 
    app: events-data
  type: ClusterIP
