---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  labels:
    app: mysql
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql-hibernate
        image: mysql:5.6
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "password"
        - name: MYSQL_DATABASE
          value: "test"
        - name: MYSQL_USER
          value: "sa"
        - name: MYSQL_PASSWORD
          value: "password"
        ports:
        - containerPort: 3306
          name: "mysql-port"
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
        
        livenessProbe:
          httpGet:
            path: /
            port: 3306
          initialDelaySeconds: 60
          periodSeconds: 60

---
apiVersion: v1
kind: Service
metadata: 
  name: mysql-service
spec: 
  ports: 
     -  port: 3306
        protocol: TCP
        targetPort: 3306
  selector: 
    app: mysql
  type: ClusterIP
